name: skelly
description: A thread-based anonymous messaging app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0+5

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  csv: ^5.0.1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_database: ^9.0.5
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  package_info_plus: ^1.3.0
  share_plus: ^3.0.4
  uni_links: ^0.5.1
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/animals.csv
